SportO/Controllers/LeagueOwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportO.Data;
using SportO_SLMS.Models;

namespace SportO.Controllers
{
    public class LeagueOwnersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeagueOwnersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LeagueOwners
        public async Task<IActionResult> Index()
        {
            var userLoggedInId = this.User.FindFirstValue(ClaimTypes.NameIdentifier); //QUery to find the Id of the user logged in
            var dbLeagueOwner = _context.LeagueOwners.Where(s => s.IdentityUserId == userLoggedInId).FirstOrDefault(); //Query to find Where the Owners IdentityUserID matches with the the userID.  Returns an object with properties
            var leagueOwnerLeagues = _context.Leagues.Include(s=>s.Sport).Where(s => s.LeagueOwnerId == dbLeagueOwner.Id).ToList(); //query to find the leagues where the leagueowner matches with the leagueowner we found in the database, which we then to list to create a list of leagues where this is true.

            return View(leagueOwnerLeagues);
        }

        // GET: LeagueOwners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leagueOwner = await _context.LeagueOwners
                .Include(l => l.Phone)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leagueOwner == null)
            {
                return NotFound();
            }

            return View(leagueOwner);
        }

        // GET: LeagueOwners/Create
        public IActionResult Create()
        {
            var leagueOwner = new LeagueOwner();
            leagueOwner = _context.LeagueOwners.Include(l => l.Phone).FirstOrDefault();
            return View(leagueOwner);
        }

        // POST: LeagueOwners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeagueOwner leagueOwner)
        {    
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                leagueOwner.IdentityUserId = userId;
                _context.Add(leagueOwner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "phoneNumber", leagueOwner.PhoneId);
            return View(leagueOwner);
        }

        // GET: LeagueOwners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leagueOwner = await _context.LeagueOwners.FindAsync(id);
            if (leagueOwner == null)
            {
                return NotFound();
            }
            ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "phoneNumber", leagueOwner.PhoneId);
            return View(leagueOwner);
        }

        // POST: LeagueOwners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,firstName,lastName,accountActive,PhoneId")] LeagueOwner leagueOwner)
        {
            if (id != leagueOwner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leagueOwner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeagueOwnerExists(leagueOwner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "phoneNumber", leagueOwner.PhoneId);
            return View(leagueOwner);
        }

        // GET: LeagueOwners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leagueOwner = await _context.LeagueOwners
                .Include(l => l.Phone)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leagueOwner == null)
            {
                return NotFound();
            }

            return View(leagueOwner);
        }

        // POST: LeagueOwners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leagueOwner = await _context.LeagueOwners.FindAsync(id);
            _context.LeagueOwners.Remove(leagueOwner);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeagueOwnerExists(int id)
        {
            return _context.LeagueOwners.Any(e => e.Id == id);
        }
    }
}

SportO/Controllers/LeaguesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportO.Data;
using SportO_SLMS.Models;

namespace SportO.Controllers
{
    public class LeaguesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeaguesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Leagues
        public async Task<IActionResult> Index()
        {
            
            return View();
        }

        // GET: Leagues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var league = await _context.Leagues
                .Include(l => l.LeagueOwner)
                .Include(l => l.Sport)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (league == null)
            {
                return NotFound();
            }

            return View(league);
        }

        // GET: Leagues/Create
        public IActionResult Create()
        {
            var league = new League();
            var sports = _context.Sports.ToList();
            ViewBag.Sport = new SelectList(sports, "Id", "type");
            return View(league);
        }

        // POST: Leagues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(League league)
        {
            if (ModelState.IsValid)
            {
                var identityUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var dbUserLoggedInId = _context.LeagueOwners.Where(l => l.IdentityUserId == identityUserId).FirstOrDefault().Id;
                league.LeagueOwnerId = dbUserLoggedInId;
                _context.Add(league);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "LeagueOwners");
            }
            ViewData["LeagueOwnerId"] = new SelectList(_context.LeagueOwners, "Id", "firstName", league.LeagueOwnerId);
            ViewData["SportId"] = new SelectList(_context.Set<Sport>(), "Id", "type", league.SportId);
            return View(league);
        }

        // GET: Leagues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var league = await _context.Leagues.FindAsync(id);
            if (league == null)
            {
                return NotFound();
            }
            ViewData["LeagueOwnerId"] = new SelectList(_context.LeagueOwners, "Id", "firstName", league.LeagueOwnerId);
            ViewData["SportId"] = new SelectList(_context.Set<Sport>(), "Id", "type", league.SportId);
            return View(league);
        }

        // POST: Leagues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,leagueName,teamCapacity,LeagueOwnerId,SportId")] League league)
        {
            if (id != league.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(league);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeagueExists(league.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LeagueOwnerId"] = new SelectList(_context.LeagueOwners, "Id", "firstName", league.LeagueOwnerId);
            ViewData["SportId"] = new SelectList(_context.Set<Sport>(), "Id", "type", league.SportId);
            return View(league);
        }

        // GET: Leagues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var league = await _context.Leagues
                .Include(l => l.LeagueOwner)
                .Include(l => l.Sport)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (league == null)
            {
                return NotFound();
            }

            return View(league);
        }

        // POST: Leagues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var league = await _context.Leagues.FindAsync(id);
            _context.Leagues.Remove(league);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeagueExists(int id)
        {
            return _context.Leagues.Any(e => e.Id == id);
        }
    }
}

SportO/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportO.Data;
using SportO_SLMS.Models;

namespace SportO.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TeamsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Teams.Include(t => t.League).Include(t => t.TeamOwner);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.League)
                .Include(t => t.TeamOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            var team = new Team();
            var leagues = _context.Leagues.ToList();
            ViewBag.League = new SelectList(leagues, "Id", "leagueName");
            return View(team);
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Team team)
        {
            var dbLeague = _context.Leagues.Where(l => l.Id == team.LeagueId).SingleOrDefault();           
               
                if (ModelState.IsValid && dbLeague.teamCapacity != 0)
                {                    
                    var identityUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var dbUserLoggedInId = _context.TeamOwners.Where(t => t.IdentityUserId == identityUserId).FirstOrDefault().Id;
                    team.TeamOwnerId = dbUserLoggedInId; 
                    _context.Add(team);
                    dbLeague.teamCapacity--;
                    await _context.SaveChangesAsync();                    
                    return RedirectToAction("Index", "TeamOwners");
                }
               
            
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "leagueName", team.LeagueId);
            ViewData["TeamOwnerId"] = new SelectList(_context.TeamOwners, "Id", "firstName", team.TeamOwnerId);
            return View(team);

        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "leagueName", team.LeagueId);
            ViewData["TeamOwnerId"] = new SelectList(_context.TeamOwners, "Id", "firstName", team.TeamOwnerId);
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,capacity,LeagueId,TeamOwnerId")] Team team)
        {
            if (id != team.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "leagueName", team.LeagueId);
            ViewData["TeamOwnerId"] = new SelectList(_context.TeamOwners, "Id", "firstName", team.TeamOwnerId);
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.League)
                .Include(t => t.TeamOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            _context.Teams.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.Id == id);
        }
    }
}

SportO/Views/LeagueOwners/Create.cshtml
@model SportO_SLMS.Models.LeagueOwner

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>LeagueOwner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <label asp-for="Phone.phoneNumber" class="control-label"></label>
                <input asp-for="Phone.phoneNumber" class ="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportO/Views/LeagueOwners/Delete.cshtml
@model SportO_SLMS.Models.LeagueOwner

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LeagueOwner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone.phoneNumber)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SportO/Views/LeagueOwners/Details.cshtml
@model SportO_SLMS.Models.LeagueOwner

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>LeagueOwner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone.phoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SportO/Views/LeagueOwners/Edit.cshtml
@model SportO_SLMS.Models.LeagueOwner

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>LeagueOwner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneId" class="control-label"></label>
                <select asp-for="PhoneId" class="form-control" asp-items="ViewBag.PhoneId"></select>
                <span asp-validation-for="PhoneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportO/Views/LeagueOwners/Index.cshtml
@model IEnumerable<SportO_SLMS.Models.League>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1></h1>

<p>
    <a asp-action="Create" asp-controller="Leagues">Create New League</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.leagueName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sport.type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.leagueName, "Index", "Teams", new { id = item.Id }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sport.type)
                </td>
                <td>
                    <a asp-action="GenerateMatches" asp-controller="Matches" asp-route-id="@item.Id">Generate Matches</a> |
                    <a asp-action="Edit" asp-controller="Leagues" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-controller="Leagues" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-controller="Leagues" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>