SportO/Controllers/RostersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportO.Data;
using SportO_SLMS.Models;

namespace SportO.Controllers
{
    public class RostersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RostersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rosters
        public async Task<IActionResult> Index(int id)
        {
            var roster = _context.Rosters.Include(r => r.Player).Include(r => r.Team).Where(r => r.TeamId == id);
            return View(roster);
        }

        // GET: Rosters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roster = await _context.Rosters
                .Include(r => r.Player)
                .Include(r => r.Team)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (roster == null)
            {
                return NotFound();
            }

            return View(roster);
        }

        // GET: Rosters/Create
        public IActionResult Create()
        {
            var roster = new Roster();
            var teams = _context.Teams.ToList();
            ViewBag.Teams = new SelectList(teams, "Id", "name");

            return View(roster);
        }

        // POST: Rosters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Roster roster)
        {
            var team = _context.Teams.Where(t => t.Id == roster.TeamId).SingleOrDefault();
            if (ModelState.IsValid && team.capacity != 0)
            {
                var identityUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var dbUserId = _context.Players.Where(p => p.IdentityUserId == identityUserId).FirstOrDefault().Id;
                roster.PlayerId = dbUserId;
                team.capacity--;
                _context.Add(roster);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Players");
            }
            ViewData["PlayerId"] = new SelectList(_context.Players, "Id", "firstName", roster.PlayerId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "name", roster.TeamId);
            return View(roster);
        }

        // GET: Rosters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roster = await _context.Rosters.FindAsync(id);
            if (roster == null)
            {
                return NotFound();
            }
            ViewData["PlayerId"] = new SelectList(_context.Players, "Id", "firstName", roster.PlayerId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "name", roster.TeamId);
            return View(roster);
        }

        // POST: Rosters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,playingPosition,kitNumber,TeamId,PlayerId")] Roster roster)
        {
            if (id != roster.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roster);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RosterExists(roster.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "TeamOwners");
            }
            ViewData["PlayerId"] = new SelectList(_context.Players, "Id", "firstName", roster.PlayerId);
            ViewData["TeamId"] = new SelectList(_context.Teams, "Id", "name", roster.TeamId);
            return View(roster);
        }

        // GET: Rosters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roster = await _context.Rosters
                .Include(r => r.Player)
                .Include(r => r.Team)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (roster == null)
            {
                return NotFound();
            }

            return View(roster);
        }

        // POST: Rosters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roster = await _context.Rosters.FindAsync(id);
            _context.Rosters.Remove(roster);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RosterExists(int id)
        {
            return _context.Rosters.Any(e => e.Id == id);
        }
    }
}

SportO/Controllers/TeamOwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportO.Data;
using SportO_SLMS.Models;

namespace SportO.Controllers
{
    public class TeamOwnersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TeamOwnersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TeamOwners
        public async Task<IActionResult> Index()
        {
            var userLoggedIn = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var dbTeamOwner = _context.TeamOwners.Where(x => x.IdentityUserId == userLoggedIn).FirstOrDefault();
            var teamOwnerTeams = _context.Teams.Where(x => x.TeamOwnerId == dbTeamOwner.Id).ToList(); 
            return View(teamOwnerTeams);
        }

        // GET: TeamOwners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teamOwner = await _context.TeamOwners
                .Include(t => t.Phone)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teamOwner == null)
            {
                return NotFound();
            }

            return View(teamOwner);
        }

        // GET: TeamOwners/Create
        public IActionResult Create()
        {
            var teamOwner = new TeamOwner();
            teamOwner = _context.TeamOwners.Include(l => l.Phone).FirstOrDefault();
            return View(teamOwner);
        }

        // POST: TeamOwners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeamOwner teamOwner)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                teamOwner.IdentityUserId = userId;
                _context.Add(teamOwner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "phoneNumber", teamOwner.PhoneId);
            return View(teamOwner);
        }

        // GET: TeamOwners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teamOwner = await _context.TeamOwners.FindAsync(id);
            if (teamOwner == null)
            {
                return NotFound();
            }
            ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "phoneNumber", teamOwner.PhoneId);
            return View(teamOwner);
        }

        // POST: TeamOwners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,firstName,lastName,accountActive,PhoneId")] TeamOwner teamOwner)
        {
            if (id != teamOwner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teamOwner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamOwnerExists(teamOwner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "phoneNumber", teamOwner.PhoneId);
            return View(teamOwner);
        }

        // GET: TeamOwners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teamOwner = await _context.TeamOwners
                .Include(t => t.Phone)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teamOwner == null)
            {
                return NotFound();
            }

            return View(teamOwner);
        }

        // POST: TeamOwners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teamOwner = await _context.TeamOwners.FindAsync(id);
            _context.TeamOwners.Remove(teamOwner);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamOwnerExists(int id)
        {
            return _context.TeamOwners.Any(e => e.Id == id);
        }
        
    }
}

SportO/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportO.Data;
using SportO_SLMS.Models;

namespace SportO.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TeamsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Teams.Include(t => t.League).Include(t => t.TeamOwner);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.League)
                .Include(t => t.TeamOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            var team = new Team();
            var leagues = _context.Leagues.ToList();
            ViewBag.League = new SelectList(leagues, "Id", "leagueName");
            return View(team);
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Team team)
        {
            var dbLeague = _context.Leagues.Where(l => l.Id == team.LeagueId).SingleOrDefault();           
               
                if (ModelState.IsValid && dbLeague.teamCapacity != 0)
                {                    
                    var identityUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var dbUserLoggedInId = _context.TeamOwners.Where(t => t.IdentityUserId == identityUserId).FirstOrDefault().Id;
                    team.TeamOwnerId = dbUserLoggedInId; 
                    _context.Add(team);
                    dbLeague.teamCapacity--;
                    await _context.SaveChangesAsync();                    
                    return RedirectToAction("Index", "TeamOwners");
                }
               
            
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "leagueName", team.LeagueId);
            ViewData["TeamOwnerId"] = new SelectList(_context.TeamOwners, "Id", "firstName", team.TeamOwnerId);
            return View(team);

        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "leagueName", team.LeagueId);
            ViewData["TeamOwnerId"] = new SelectList(_context.TeamOwners, "Id", "firstName", team.TeamOwnerId);
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,capacity,LeagueId,TeamOwnerId")] Team team)
        {
            if (id != team.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "leagueName", team.LeagueId);
            ViewData["TeamOwnerId"] = new SelectList(_context.TeamOwners, "Id", "firstName", team.TeamOwnerId);
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.League)
                .Include(t => t.TeamOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            _context.Teams.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.Id == id);
        }
    }
}

SportO/Views/TeamOwners/Create.cshtml
@model SportO_SLMS.Models.TeamOwner

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>TeamOwner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone.phoneNumber" class="control-label"></label>
                <input asp-for="Phone.phoneNumber" class="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportO/Views/TeamOwners/Delete.cshtml
@model SportO_SLMS.Models.TeamOwner

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TeamOwner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>     
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone.phoneNumber)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SportO/Views/TeamOwners/Details.cshtml
@model SportO_SLMS.Models.TeamOwner

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TeamOwner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone.phoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SportO/Views/TeamOwners/Edit.cshtml
@model SportO_SLMS.Models.TeamOwner

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>TeamOwner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="PhoneId" class="control-label"></label>
                <select asp-for="PhoneId" class="form-control" asp-items="ViewBag.PhoneId"></select>
                <span asp-validation-for="PhoneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SportO/Views/TeamOwners/Index.cshtml
@model IEnumerable<SportO_SLMS.Models.Team>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<p>
    <a asp-action="Create" asp-controller="Teams">Create New Team</a>
</p>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.name, "Index", "Rosters", new { id = item.Id}, null)
                </td>   
                <td>
                    <a asp-action="Edit" asp-controller="Teams" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-controller="Teams" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-controller="Teams" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>